accelerate launch --config_file=./accelerate_config/yao.yaml finetune.py \
    --model_name Open-Orca/Mistral-7B-OpenOrca \
    --dataset_name ./llm-science-exam-data-w-thought/train_.csv \
    --dataset_text_field text \
    --gradient_accumulation_steps 4 \
    --learning_rate 2e-4 \
    --batch_size 8 \
    --seq_length 2048 \
    --load_in_4bit True \
    --use_peft True \
    --output_dir ./output \
    --peft_lora_r 8 \
    --peft_lora_alpha 16 \
    --num_train_epochs 1 \
    --save_total_limit 2 \
    --save_steps 200 \
    --use_flash_attention_2 True \
    --neft_noise_alpha 5